from __future__ import annotations 
from unittest.mock import MagicMock, patch 
import numpy as np 
import pytest 
from src.chunking.naive_fixed_chunker import NaiveFixedChunker 
from src.chunking.semantic_chunker import SemanticChunker 
from src.chunking.structure_aware_chunker import StructureAwareChunker 
from src.shared.models import FilingMetadata, FilingType, ParsedFiling, ParsedSection 
def _make_mock_parsed_filing() -> ParsedFiling:
    """
    Helper function to generate a dummy ParsedFiling object containing basic
    metadata, a parsed text section, and a parsed table structure.
    """
    metadata = FilingMetadata(
        ticker="AAPL", 
        cik="0000320193", 
        filing_type=FilingType.TEN_K, 
        filing_date="2023-09-30", 
        fiscal_year=2023, 
        accession_number="0000320193-23-000106", 
        local_path="data/raw/AAPL/10-K_2023-09-30.html" 
    )
    sections = [
        ParsedSection(
            item_id="Item 7", 
            title="Management's Discussion and Analysis", 
            content="This is the first sentence of the financial report. It contains some basic business updates. "
                    "This is another sentence focusing on corporate research and development expenditures.", 
            tables=[
                {
                    "caption": "R&D Expense Table", 
                    "raw_text": "| Year | Expense |\n|---|---|\n| 2023 | $29.9B |\n| 2022 | $26.2B |" 
                }
            ]
        )
    ]
    return ParsedFiling(metadata=metadata, sections=sections)
def test_naive_fixed_chunker() -> None:
    """
    Verifies that the NaiveFixedChunker concatenates all document elements (text and tables)
    and segments them into fixed token slices with the expected index sequence.
    """
    chunker = NaiveFixedChunker(chunk_size=15, overlap_fraction=0.1)
    filing = _make_mock_parsed_filing()
    chunks = chunker.chunk(filing)
    assert len(chunks) > 0, "No chunks were generated by the NaiveFixedChunker."
    first_chunk = chunks[0]
    assert len(first_chunk.text) > 0, "Chunk text content is empty."
    assert first_chunk.strategy.value == "naive_fixed", "Strategy label does not match naive_fixed."
    assert first_chunk.chunk_index == 0, "Initial chunk index is not 0."
def test_structure_aware_chunker() -> None:
    """
    Verifies that the StructureAwareChunker divides text along section/header boundaries,
    treats tables as isolated chunks, and prepends item headers to each chunk.
    """
    chunker = StructureAwareChunker(max_tokens=50)
    filing = _make_mock_parsed_filing()
    chunks = chunker.chunk(filing)
    assert len(chunks) >= 2, "Expected at least 2 chunks (one text chunk and one table chunk)."
    table_chunks = [c for c in chunks if c.is_table]
    assert len(table_chunks) == 1, "Expected exactly one isolated table chunk."
    assert "R&D Expense Table" in table_chunks[0].text, "Table caption is missing from the table chunk."
    text_chunks = [c for c in chunks if not c.is_table]
    assert "[Item 7. Management's Discussion and Analysis]" in text_chunks[0].text,        "Expected the section item header to be prepended to the text chunk."
@patch("src.chunking.semantic_chunker.SentenceTransformer")
def test_semantic_chunker(mock_transformer_class: MagicMock) -> None:
    """
    Verifies that the SemanticChunker tokenizes sentences and groups them
    based on the similarity scores computed from mock embeddings.
    """
    mock_model = MagicMock()
    mock_transformer_class.return_value = mock_model
    v1 = np.array([1.0, 0.0, 0.0]) 
    v2 = np.array([0.9, 0.1, 0.0]) 
    v3 = np.array([0.0, 1.0, 0.0]) 
    mock_model.encode.return_value = np.array([v1, v2, v3])
    chunker = SemanticChunker(similarity_threshold=0.5, min_tokens=5)
    filing = _make_mock_parsed_filing()
    chunks = chunker.chunk(filing)
    assert len(chunks) > 0, "No chunks were generated by the SemanticChunker."
    assert chunks[0].strategy.value == "semantic", "Strategy label does not match semantic."
