# tests/unit/test_chunkers.py
# This module implements unit tests for the chunker strategies.
# We test NaiveFixedChunker, StructureAwareChunker, and SemanticChunker to ensure
# that they divide raw parsed filings into structured, bounded text blocks correctly.

from __future__ import annotations # Allow self-referencing type annotations.
from unittest.mock import MagicMock, patch # Standard library mock utilities to isolate tests from heavy model downloads.
import numpy as np # Library for numerical array operations.
import pytest # Testing framework.
from src.chunking.naive_fixed_chunker import NaiveFixedChunker # Subject under test.
from src.chunking.semantic_chunker import SemanticChunker # Subject under test.
from src.chunking.structure_aware_chunker import StructureAwareChunker # Subject under test.
from src.shared.models import FilingMetadata, FilingType, ParsedFiling, ParsedSection # Data contracts.


# Create a shared helper to construct a mock ParsedFiling object.
def _make_mock_parsed_filing() -> ParsedFiling:
    """
    Helper function to generate a dummy ParsedFiling object containing basic
    metadata, a parsed text section, and a parsed table structure.
    """
    # Create filing metadata details.
    metadata = FilingMetadata(
        ticker="AAPL", # Ticker symbol of the company.
        cik="0000320193", # Central Index Key code.
        filing_type=FilingType.TEN_K, # 10-K filing type.
        filing_date="2023-09-30", # Date when filed.
        fiscal_year=2023, # Fiscal year of the document.
        accession_number="0000320193-23-000106", # Unique accession sequence number.
        local_path="data/raw/AAPL/10-K_2023-09-30.html" # Dummy path on disk.
    )

    # Define a single text section with simple sentences.
    sections = [
        ParsedSection(
            item_id="Item 7", # SEC Item section identifier.
            title="Management's Discussion and Analysis", # Title of the section.
            content="This is the first sentence of the financial report. It contains some basic business updates. "
                    "This is another sentence focusing on corporate research and development expenditures.", # Main paragraph content.
            tables=[
                {
                    "caption": "R&D Expense Table", # Table caption.
                    "raw_text": "| Year | Expense |\n|---|---|\n| 2023 | $29.9B |\n| 2022 | $26.2B |" # Simulated table as markdown text.
                }
            ]
        )
    ]

    # Return the assembled ParsedFiling document model.
    return ParsedFiling(metadata=metadata, sections=sections)


def test_naive_fixed_chunker() -> None:
    """
    Verifies that the NaiveFixedChunker concatenates all document elements (text and tables)
    and segments them into fixed token slices with the expected index sequence.
    """
    # Instantiate the naive chunker with a small chunk size of 15 tokens and 0.1 (10%) overlap.
    chunker = NaiveFixedChunker(chunk_size=15, overlap_fraction=0.1)
    
    # Generate the mock filing.
    filing = _make_mock_parsed_filing()
    
    # Process the filing through the chunker.
    chunks = chunker.chunk(filing)
    
    # Verify that we retrieved multiple chunks.
    assert len(chunks) > 0, "No chunks were generated by the NaiveFixedChunker."
    
    # Validate the structure and properties of the first chunk.
    first_chunk = chunks[0]
    # Check that the chunk contains text content.
    assert len(first_chunk.text) > 0, "Chunk text content is empty."
    # Verify that the indexing strategy matches.
    assert first_chunk.strategy.value == "naive_fixed", "Strategy label does not match naive_fixed."
    # Verify that chunk indices are sequential starting from 0.
    assert first_chunk.chunk_index == 0, "Initial chunk index is not 0."


def test_structure_aware_chunker() -> None:
    """
    Verifies that the StructureAwareChunker divides text along section/header boundaries,
    treats tables as isolated chunks, and prepends item headers to each chunk.
    """
    # Initialize the structure-aware chunker with a 50-token threshold.
    chunker = StructureAwareChunker(max_tokens=50)
    
    # Generate mock filing data.
    filing = _make_mock_parsed_filing()
    
    # Extract structural chunks.
    chunks = chunker.chunk(filing)
    
    # Expect at least two chunks: one for the Item 7 text and one for the R&D table.
    assert len(chunks) >= 2, "Expected at least 2 chunks (one text chunk and one table chunk)."
    
    # Find the table chunk by filtering on the is_table boolean.
    table_chunks = [c for c in chunks if c.is_table]
    # Check that we found exactly one table chunk.
    assert len(table_chunks) == 1, "Expected exactly one isolated table chunk."
    # Verify that the table text contains the table data.
    assert "R&D Expense Table" in table_chunks[0].text, "Table caption is missing from the table chunk."
    
    # Check that the text chunks prepended the section Item ID and title.
    text_chunks = [c for c in chunks if not c.is_table]
    assert "[Item 7. Management's Discussion and Analysis]" in text_chunks[0].text, \
        "Expected the section item header to be prepended to the text chunk."


# Mock the SentenceTransformer model class to bypass downloading the weights.
@patch("src.chunking.semantic_chunker.SentenceTransformer")
def test_semantic_chunker(mock_transformer_class: MagicMock) -> None:
    """
    Verifies that the SemanticChunker tokenizes sentences and groups them
    based on the similarity scores computed from mock embeddings.
    """
    # Create a mock instance of the SentenceTransformer.
    mock_model = MagicMock()
    # Configure the class mock to return our mock model instance when initialized.
    mock_transformer_class.return_value = mock_model
    
    # Setup dummy embeddings for three sentences.
    # The first two sentences are semantically identical (high similarity).
    # The third sentence is completely orthogonal (low similarity).
    v1 = np.array([1.0, 0.0, 0.0]) # Direction 1.
    v2 = np.array([0.9, 0.1, 0.0]) # Direction 1 (very close).
    v3 = np.array([0.0, 1.0, 0.0]) # Direction 2 (perpendicular).
    
    # Assign the mock model's encode function to return these three vectors.
    mock_model.encode.return_value = np.array([v1, v2, v3])
    
    # Initialize the semantic chunker with a 0.5 similarity threshold and 5-token minimum.
    chunker = SemanticChunker(similarity_threshold=0.5, min_tokens=5)
    
    # Generate mock filing.
    filing = _make_mock_parsed_filing()
    
    # Segment the filing semantically.
    chunks = chunker.chunk(filing)
    
    # Verify that the chunker successfully produced chunks.
    assert len(chunks) > 0, "No chunks were generated by the SemanticChunker."
    # Verify that the strategy matches.
    assert chunks[0].strategy.value == "semantic", "Strategy label does not match semantic."
